import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const html = readFileSync(new URL('../public/index.html', import.meta.url), 'utf8');
test('Commission Rider exposes clickable arrival and order status count navigators', () => {
  assert.match(html, /function commissionStatusNavigatorsMarkup\(panel\)/);
  assert.match(html, /<strong>Arrival status<\/strong>/);
  assert.match(html, /<strong>Order status<\/strong>/);
  assert.match(html, /class="commission-status-navigators finance-arrange-container"[^>]*data-visual-role="status-navigation"/);
  assert.match(html, /class="commission-status-navigator finance-visual"[^>]*data-visual-key="\$\{esc\(panel\.id\)\}:status:arrival"[^>]*data-default-columns="4"/);
  assert.match(html, /class="commission-status-navigator finance-visual"[^>]*data-visual-key="\$\{esc\(panel\.id\)\}:status:order"[^>]*data-default-columns="8"/);
  assert.match(html, /\.commission-status-navigators\.finance-arrange-container\.visual-stack-layout/);
  assert.match(html, /\.commission-status-navigator\.finance-visual > \.commission-status-visual-head > \.visual-move-handle/);
  assert.match(html, /\.commission-status-navigators\.finance-arrange-container"\)/);
  assert.match(html, /grid\?\.dataset\.visualRole \? `\$\{panelId\}:\$\{grid\.dataset\.visualRole\}` : panelId/);
  assert.match(html, /:scope > \.commission-status-visual-head/);
  assert.match(html, /\.commission-status-navigator > header \{[^}]*justify-content: flex-start;/);
  assert.match(html, /\.commission-status-navigator > header \{[^}]*gap: 6px;/);
  assert.match(html, /data-commission-table-status=/);
  assert.match(html, /grafanaSavedFilterValues\(panel\.id, "order_status"\)/);
  assert.match(html, /const orderOptions = orderValues\.map/);
  assert.match(html, /\$\{orderOptions\}/);
  assert.match(html, /if \(existing >= 0\) values\.splice\(existing, 1\); else values\.push\(value\)/);
  assert.match(html, /state\.tableColumnFilters\[tableId\]\[key\] = \{ mode: "include", values \}/);
  assert.match(html, /primaryTableRows\(panel, "arrival_status"\)/);
  assert.match(html, /primaryTableRows\(panel, "order_status"\)/);
  const handler = html.match(/const commissionStatusButton = event\.target\.closest\("\[data-commission-table-status\]"\);([\s\S]*?)const exceptionModeButton/)[1];
  assert.doesNotMatch(handler, /scrollIntoView/);
});
